import { useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FileText, Copy, Download, Trash2, RefreshCw, CheckCircle, Clock } from 'lucide-react'
import type { TranscriptEntry } from '../types'
import styles from './TranscriptPanel.module.css'

interface Props {
  entries:     TranscriptEntry[]
  onClear:     () => void
  onDemoReset: () => void
}

// ── Clean protocol text ───────────────────────────────────────────────────────

function buildProtocolText(entries: TranscriptEntry[]): string {
  const session = `FST-${Date.now().toString(36).toUpperCase().slice(-6)}`
  const date    = new Date().toLocaleDateString('en-GB')

  const lines = [
    'FORENSIC SIGN TRANSLATION PROTOCOL',
    '─'.repeat(44),
    `Session : ${session}`,
    `Date    : ${date}`,
    `Mode    : Uzbek Emergency Sign Mode`,
    `Entries : ${entries.length}`,
    '─'.repeat(44),
    '',
    ...[...entries].reverse().map((e, i) =>
      `${String(i + 1).padStart(2, '0')}. [${e.timestamp}]  ${e.translation}  (${e.confidence}%)`
    ),
    '',
    '─'.repeat(44),
    'Generated by Forensic Sign Translator v2.4.1',
  ]

  return lines.join('\n')
}

function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text).catch(() => {
    const el = document.createElement('textarea')
    el.value = text
    document.body.appendChild(el)
    el.select()
    document.execCommand('copy')
    document.body.removeChild(el)
  })
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function TranscriptPanel({ entries, onClear, onDemoReset }: Props) {
  const listRef         = useRef<HTMLDivElement | null>(null)
  const prevLengthRef   = useRef(0)
  const [copied, setCopied] = useState(false)

  // Auto-scroll only when a new entry is added
  useEffect(() => {
    if (entries.length > prevLengthRef.current && listRef.current) {
      listRef.current.scrollTop = 0   // newest is at top
    }
    prevLengthRef.current = entries.length
  }, [entries.length])

  function handleCopy() {
    copyToClipboard(buildProtocolText(entries))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleExport() {
    const text = buildProtocolText(entries)
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `FST-Protocol-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className={styles.panel}>
      {/* ── Header ── */}
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <FileText size={14} strokeWidth={1.5} />
          <span className={styles.title}>Protocol Draft</span>
          {entries.length > 0 && (
            <span className={styles.count}>{entries.length}</span>
          )}
        </div>
        <div className={styles.actions}>
          <motion.button
            className={`${styles.actionBtn} ${copied ? styles.actionBtnSuccess : ''}`}
            onClick={handleCopy}
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            disabled={entries.length === 0}
          >
            {copied ? <><CheckCircle size={11} strokeWidth={2} /> Copied!</> : <><Copy size={11} strokeWidth={2} /> Copy</>}
          </motion.button>

          <motion.button
            className={styles.actionBtn}
            onClick={handleExport}
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            disabled={entries.length === 0}
          >
            <Download size={11} strokeWidth={2} />
            Export TXT
          </motion.button>

          <motion.button
            className={`${styles.actionBtn} ${styles.actionBtnDanger}`}
            onClick={onClear}
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
            disabled={entries.length === 0}
          >
            <Trash2 size={11} strokeWidth={2} />
            Clear
          </motion.button>

          <motion.button
            className={`${styles.actionBtn} ${styles.actionBtnReset}`}
            onClick={onDemoReset}
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.96 }}
          >
            <RefreshCw size={11} strokeWidth={2} />
            Demo Reset
          </motion.button>
        </div>
      </div>

      {/* ── Body ── */}
      <div className={styles.body} ref={listRef}>
        <AnimatePresence>
          {entries.length === 0 ? (
            <motion.div className={styles.emptyState}
              initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              <FileText size={26} strokeWidth={1} style={{ color: 'rgba(0,212,255,0.12)' }} />
              <p>Protocol is empty</p>
              <span>Locked gestures will appear here</span>
            </motion.div>
          ) : (
            <div className={styles.list}>
              {entries.map((entry, idx) => (
                <motion.div
                  key={entry.id}
                  className={styles.row}
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.25 }}
                  layout
                >
                  {/* Index */}
                  <span className={styles.rowNum}>
                    {String(entries.length - idx).padStart(2, '0')}
                  </span>

                  {/* Timestamp */}
                  <div className={styles.rowTime}>
                    <Clock size={9} strokeWidth={2} />
                    {entry.timestamp}
                  </div>

                  {/* Translation — primary content */}
                  <p className={styles.rowPhrase}>{entry.translation}</p>

                  {/* Confidence badge */}
                  <span className={`${styles.confBadge} ${
                    entry.confidence >= 85 ? styles.confGreen :
                    entry.confidence >= 65 ? styles.confBlue  : styles.confRed
                  }`}>
                    {entry.confidence}%
                  </span>
                </motion.div>
              ))}
            </div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}
