import type { TranscriptEntry } from '../types'
import { MODE_LABEL, formatProtocolDate } from './session'

export function buildProtocolText(entries: TranscriptEntry[], sessionId: string) {
  const lines = [
    'FORENSIC SIGN TRANSLATION PROTOCOL',
    '',
    `Session: ${sessionId}`,
    `Date: ${formatProtocolDate()}`,
    `Mode: ${MODE_LABEL}`,
    '',
  ]

  if (entries.length === 0) {
    lines.push('No locked gestures recorded.')
  } else {
    entries.forEach((entry, index) => {
      lines.push(`${index + 1}. [${entry.timestamp}] ${entry.translation}`)
    })
  }

  lines.push('', 'Generated by Forensic Sign Translator')

  return lines.join('\n')
}

export async function copyText(text: string) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text)
    return
  }

  const textarea = document.createElement('textarea')
  textarea.value = text
  document.body.appendChild(textarea)
  textarea.select()
  document.execCommand('copy')
  document.body.removeChild(textarea)
}

export function exportProtocolText(text: string, sessionId: string) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = `${sessionId}-${formatProtocolDate().replace(/\./g, '-')}.txt`
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}
